const fs = require('fs');
const os = require('os');

function getLocalIPv4() {
  const nets = os.networkInterfaces();
  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      // Skip over non-IPv4 and internal (i.e. 127.0.0.1) addresses
      if (net.family === 'IPv4' && !net.internal) {
        return net.address;
      }
    }
  }
  return null;
}

// Allow passing a specific API URL as a command-line argument (e.g. node scripts/set-api-url.js http://10.0.2.2:4000)
const provided = process.argv[2];
let apiUrl;
if (provided) {
  // Use the provided URL as-is (trim trailing slash)
  apiUrl = provided.replace(/\/$/, '');
} else {
  const ip = getLocalIPv4() || 'localhost';
  apiUrl = `http://${ip}:4000`;
}

const content = `// This file is auto-generated by scripts/set-api-url.js\nexport const API_URL = '${apiUrl}';\n`;

fs.writeFileSync('app/config.ts', content, 'utf8');
console.log('Wrote app/config.ts with API_URL =', apiUrl);
